aliases:
  - &containerize
    name: Containerize
    command: |
      docker build -t aeternas/swadeshness-nginx:latest && \
      docker push aeternas/swadeshness:latest
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: true
version: 2
jobs:
  build:
    docker:
      - image: golang:1.11

    steps:
      - checkout
      - *setup-remote-docker
      - run: *containerize
