aliases:
  - &containerize
    name: Containerize
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build -t aeternas/swadeshness-nginx:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-nginx:$CIRCLE_BRANCH
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: true
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - *setup-remote-docker
      - run: *containerize
workflows:
  version: 2.1
  build-containerize-push:
    jobs:
      - build
