aliases:
  - &git-checkout
    name: Checkout
    command: |
      mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git reset --hard $CIRCLE_SHA1
  - &golang-docker-image
    - image: circleci/golang:$GOLANG_VERSION
  - &containerize
    name: Containerize
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build -t aeternas/swadeshness-nginx:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-nginx:$CIRCLE_BRANCH
      if [[ $CIRCLE_BRANCH == "master" ]]; then
        docker tag aeternas/swadeshness-nginx:master aeternas/swadeshness-nginx:latest && \
        docker push aeternas/swadeshness-nginx:latest
      fi
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: false
version: 2.1
jobs:
  build-containerize-push:
    docker: *golang-docker-image
    resource_class: small
    steps:
      - run: *git-checkout
      - *setup-remote-docker
      - run: *containerize
workflows:
  version: 2.1
  build-containerize-push:
    jobs:
      - build-containerize-push
