aliases:
  - &containerize
    name: Containerize
    command: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
      docker build -t aeternas/swadeshness-nginx:latest . && \
      docker push aeternas/swadeshness-nginx:latest
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: true
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - *setup-remote-docker
      - run: *containerize
