aliases:
  - &containerize
    name: Containerize
    command: |
      docker build -t aeternas/swadeshness-nginx:latest && \
      docker puch aeternas/swadeshness:latest
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run: *containerize
